version: '3'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - local
    user: "clickhouse:clickhouse"
    volumes:
      - ./config/users.xml:/etc/clickhouse-server/users.xml

  binance_client:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: binance_client_application
    restart: always
    depends_on:
      - clickhouse-server
    networks:
      - local

networks:
  local:
