version: '3'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - local

  clickhouse-client:
    image: yandex/clickhouse-client
    container_name: clickhouse-client
    depends_on:
      - clickhouse-server
    command: ["--host", "clickhouse-server"]
    links:
      - clickhouse-server
    stdin_open: true
    tty: true
    networks:
      - local

  images_publisher_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: binance_client_application
    restart: always
    depends_on:
      - clickhouse-server
    networks:
      - local

networks:
  local:
